<a href="https://colab.research.google.com/github/seijimorimoto/CE888-Data-Science/blob/master/Lab1/CE888_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Lab 1. Introduction to Numerical Computing with Numpy and Matplotlib**

###**1. Create a (4 x 2) integer array and print it's attributes**

In [1]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print('x:')
print(x)
print('\nDimensions of x =', x.ndim)
print('Type of data stored in x =', x.dtype)
print('Number of elements in x =', x.size)
print('Byte size of each element in x =', x.itemsize)
print('Total byte size of x =', x.nbytes)

x:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Dimensions of x = 2
Type of data stored in x = int64
Number of elements in x = 8
Byte size of each element in x = 8
Total byte size of x = 64


###**2. Create an array of dimension (1,10) and sort it in ascending and descending order**

In [2]:
x = np.array([5, 4, 6, 3, 7, 2, 8, 1, 9, 0])
print('Original array:', x)
x = np.sort(x)
print('Array sorted in ascending order:', x)
x[::-1].sort()
print('Array sorted in descending order:', x)

Original array: [5 4 6 3 7 2 8 1 9 0]
Array sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]
Array sorted in descending order: [9 8 7 6 5 4 3 2 1 0]


###**3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]**

In [3]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print('Original array:', x)
print('Array reshaped to have 3x3 shape:')
print(np.reshape(x, (3, 3)))

Original array: [1 2 3 4 5 6 7 8 9]
Array reshaped to have 3x3 shape:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


###**4. Stack two arrays of any size horizontally and vertically**

In [4]:
x = np.random.randint(1, 10, 10)
y = np.random.randint(100, 200, 10)
print('Original arrays:')
print(x)
print(y)
print('\nArrays stacked horizontally:')
print(np.stack((x, y), axis=0))
print('\nArrays stacked vertically:')
print(np.stack((x, y), axis=-1))

Original arrays:
[8 7 4 1 4 5 8 6 8 1]
[142 197 129 178 190 148 190 138 126 137]

Arrays stacked horizontally:
[[  8   7   4   1   4   5   8   6   8   1]
 [142 197 129 178 190 148 190 138 126 137]]

Arrays stacked vertically:
[[  8 142]
 [  7 197]
 [  4 129]
 [  1 178]
 [  4 190]
 [  5 148]
 [  8 190]
 [  6 138]
 [  8 126]
 [  1 137]]


###**5. Create two arrays of same size and find commom elements**

In [5]:
x = np.random.randint(1, 10, 5)
y = np.random.randint(1, 10, 5)
print('Array 1:', x)
print('Array 2:', y)
print('Common elements:', np.intersect1d(x, y))

Array 1: [8 2 9 4 4]
Array 2: [8 7 3 8 9]
Common elements: [8 9]


###**6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column**

In [6]:
x = np.random.randint(1, 100, (5, 5))
print('Original Array:')
print(x)
print('\nMin values from each row:', np.amin(x, axis=1))
print('Min values from each column:', np.amin(x, axis=0))
print('Max values from each row:', np.amax(x, axis=1))
print('Max values from each column:', np.amax(x, axis=0))

Original Array:
[[44 35 57  8 55]
 [53 23 53 28 35]
 [67 80 72 98 56]
 [33 90 98  6 27]
 [13 25 65 18 81]]

Min values from each row: [ 8 23 56  6 13]
Min values from each column: [13 23 53  6 27]
Max values from each row: [57 53 98 98 81]
Max values from each column: [67 90 98 98 81]


###**7. Create an array of size 100 and compute the mean, median, standard deviation**

In [7]:
x = np.random.randint(1, 1000, 100)
print('Array:', x)
print('Mean:', np.mean(x))
print('Median:', np.median(x))
print('Std Deviation:', np.std(x))

Array: [286 741   8  63  40   7 286 721 476 898 261 423 360 271 366  25 390 596
 862 188 497 433 568 261 166 559 416 394 798   8 314 195 870 257 528 161
 195 842 404 817 892 852 500 489 385 882 200 644 135 496  24 373  15 576
 403 163 610 139 476 581  59 199 977 845 167 525  68 314 610 884 927 622
 283 268 702 427 971 803 662 686 538 642 522 302 894 775 736 161 101 645
 827  59  96 541 584 803 114 918 124 116]
Mean: 452.83
Median: 430.0
Std Deviation: 283.56509146931324


###**8. Normalize a 5x5 random matrix**

In [8]:
x = np.random.randint(0, 43, (5, 5))
print('Original Array:')
print(x)
y = (x - x.min()) / (x.max() - x.min())
print('\nNormalized Array:')
print(y)

Original Array:
[[12 22  2 31 20]
 [15  6 34 38  4]
 [23  6 12  6  7]
 [41 39 28 14 42]
 [ 2 40 41  9  9]]

Normalized Array:
[[0.25  0.5   0.    0.725 0.45 ]
 [0.325 0.1   0.8   0.9   0.05 ]
 [0.525 0.1   0.25  0.1   0.125]
 [0.975 0.925 0.65  0.3   1.   ]
 [0.    0.95  0.975 0.175 0.175]]


###**9. Consider an array of dimension (4,4,3), how to multiply it by an array with dimensions (4,4)?**

In [9]:
x = np.random.randint(0, 43, (4, 4, 3))
y = np.random.randint(0, 43, (4, 4))
print('Original arrays:')
print(x)
print()
print(y)
z = np.zeros((4, 4, 3))
for i in range(3):
  z[:, :, i] = x[:, :, i] * y
print('\nArrays multiplication:')
print(z)

Original arrays:
[[[20 20 15]
  [ 0 29 12]
  [24 32 23]
  [23  2 40]]

 [[40 37  6]
  [39 27 24]
  [24  7  5]
  [ 5 11  3]]

 [[27 26  4]
  [18 22 20]
  [22 20  8]
  [ 7  5 31]]

 [[ 5 34 42]
  [21 38  2]
  [16 23 38]
  [ 2 29 34]]]

[[21 35 42 27]
 [20 15 39 16]
 [25 23  3 24]
 [29 38 37 29]]

Arrays multiplication:
[[[ 420.  420.  315.]
  [   0. 1015.  420.]
  [1008. 1344.  966.]
  [ 621.   54. 1080.]]

 [[ 800.  740.  120.]
  [ 585.  405.  360.]
  [ 936.  273.  195.]
  [  80.  176.   48.]]

 [[ 675.  650.  100.]
  [ 414.  506.  460.]
  [  66.   60.   24.]
  [ 168.  120.  744.]]

 [[ 145.  986. 1218.]
  [ 798. 1444.   76.]
  [ 592.  851. 1406.]
  [  58.  841.  986.]]]
